package com.junruyi.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.junruyi.entities.EquipMent;
import com.junruyi.entities.Wifi;
import com.junruyi.entities.Location;

import com.junruyi.dao.EquipMentDao;
import com.junruyi.dao.WifiDao;
import com.junruyi.dao.LocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig equipMentDaoConfig;
    private final DaoConfig wifiDaoConfig;
    private final DaoConfig locationDaoConfig;

    private final EquipMentDao equipMentDao;
    private final WifiDao wifiDao;
    private final LocationDao locationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        equipMentDaoConfig = daoConfigMap.get(EquipMentDao.class).clone();
        equipMentDaoConfig.initIdentityScope(type);

        wifiDaoConfig = daoConfigMap.get(WifiDao.class).clone();
        wifiDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        equipMentDao = new EquipMentDao(equipMentDaoConfig, this);
        wifiDao = new WifiDao(wifiDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);

        registerDao(EquipMent.class, equipMentDao);
        registerDao(Wifi.class, wifiDao);
        registerDao(Location.class, locationDao);
    }
    
    public void clear() {
        equipMentDaoConfig.getIdentityScope().clear();
        wifiDaoConfig.getIdentityScope().clear();
        locationDaoConfig.getIdentityScope().clear();
    }

    public EquipMentDao getEquipMentDao() {
        return equipMentDao;
    }

    public WifiDao getWifiDao() {
        return wifiDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

}
