package com.junruyi.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EQUIP_MENT".
 */
public class EquipMent {

    private Long id;
    private String equipMentAddress;
    private String equipMentName;
    private Integer equipMentLogo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EquipMent() {
    }

    public EquipMent(Long id) {
        this.id = id;
    }

    public EquipMent(Long id, String equipMentAddress, String equipMentName, Integer equipMentLogo) {
        this.id = id;
        this.equipMentAddress = equipMentAddress;
        this.equipMentName = equipMentName;
        this.equipMentLogo = equipMentLogo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEquipMentAddress() {
        return equipMentAddress;
    }

    public void setEquipMentAddress(String equipMentAddress) {
        this.equipMentAddress = equipMentAddress;
    }

    public String getEquipMentName() {
        return equipMentName;
    }

    public void setEquipMentName(String equipMentName) {
        this.equipMentName = equipMentName;
    }

    public Integer getEquipMentLogo() {
        return equipMentLogo;
    }

    public void setEquipMentLogo(Integer equipMentLogo) {
        this.equipMentLogo = equipMentLogo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
