package com.junruyi.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "WIFI".
 */
public class Wifi {

    private Long id;
    private String wifiName;
    private String bssid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Wifi() {
    }

    public Wifi(Long id) {
        this.id = id;
    }

    public Wifi(Long id, String wifiName, String bssid) {
        this.id = id;
        this.wifiName = wifiName;
        this.bssid = bssid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWifiName() {
        return wifiName;
    }

    public void setWifiName(String wifiName) {
        this.wifiName = wifiName;
    }

    public String getBssid() {
        return bssid;
    }

    public void setBssid(String bssid) {
        this.bssid = bssid;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
